version: 2
updates:
  - package-ecosystem: "github-actions"
    allow:
      - dependency-type: "all"
    assignees:
      - dependabot[bot]
    directory: "/"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    allow:
      - dependency-type: "all"
    assignees:
      - dependabot[bot]
    directory: "/"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
