name: CVE Scan

on:
  push:
    # Workflows triggered by Dependabot on the "push" event run with read-only access.
    # Uploading Code Scanning results requires write access. We therefore only use the
    # "pull_request" trigger for Dependabot branches.
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache trivy
        uses: actions/cache@v3
        env:
          cache-name: cache-trivy
        with:
          path: ~/.cache/trivy
          key: ${{ env.cache-name }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          exit-code: 1
          format: 'sarif'
          output: 'trivy-results.sarif'
          scan-ref: '.'
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
          list-all-pkgs: 'true'
          ignore-unfixed: true

      - name: Publish results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
